# Generated by Django 3.2.5 on 2021-11-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0065_auto_20211006_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogdata',
            name='monitoring_json',
            field=models.JSONField(blank=True, help_text='JSON object representing the monitoring for the catalog.', null=True),
        ),
    ]
