# Generated by Django 3.2.5 on 2021-12-19 14:30

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    # Update set module_question_id for existing TaskAnswer
    # module_question_id is not a Django id, but is question yaml identifier string (e.g., key)
    ta_model = apps.get_model("guidedmodules", "TaskAnswer")
    db_alias = schema_editor.connection.alias
    taskanswers = ta_model.objects.all()
    for taskanswer in taskanswers:
        taskanswer.module_question_id = taskanswer.question.spec['id']
    ta_model.objects.bulk_update(taskanswers, ['module_question_id'], 100)

class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0060_alter_moduleasset_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswer',
            name='module_question_id',
            field=models.CharField(blank=True, help_text='ID of the question', max_length=200, null=True),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
