# Generated by Django 3.2.5 on 2021-12-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidedmodules', '0061_taskanswer_module_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswer',
            name='question',
            field=models.ForeignKey(help_text="The question (within the Task's Module) that this TaskAnswer is answering.", null=True, on_delete=django.db.models.deletion.PROTECT, to='guidedmodules.modulequestion'),
        ),
    ]
