# Generated by Django 3.2.13 on 2022-05-31 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0065_alter_proposal_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A UUID (a unique identifier) for this Location.')),
                ('title', models.CharField(help_text='Title of Location.', max_length=250)),
                ('address_type', models.CharField(blank=True, help_text='Type of address', max_length=250, null=True)),
                ('street', models.CharField(blank=True, help_text='Street address', max_length=250, null=True)),
                ('apt', models.CharField(blank=True, help_text='Apt/Suite', max_length=250, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=250, null=True)),
                ('state', models.CharField(blank=True, help_text='State', max_length=250, null=True)),
                ('zipcode', models.CharField(blank=True, help_text='Zip', max_length=250, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=250, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='project', to='siteapp.Tag'),
        ),
    ]
